version: "3.5"
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - .database.sql:/.database.sql
      - db_data:/var/lib/postgres

volumes:
  db_data: