version: "3.9"
services:
  postgres:
    build: .
    container_name: erp_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: erp_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

